server:
  port: 8989
  tomcat:
    basedir: I:/temp/cloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: dev
  application:
    name: service-miya
  zipkin:
    base-url: http://localhost:9411
    
#logging:
#  config: classpath:logback-cloud.xml
