spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.242:3306/minorfish-mw?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: minorfish

weixin:
  appId: wx66a9b853e6c5d53f
  appSecret: ad31690d44a06515309cd2a36c1c8f87
  componentAppId: wxb5f546668d672a96
  redis:
    host: 192.168.2.227
    port: 6379
    timeout: 5000
    password: admin123
    database: 0
